In [45]:
import pandas as pd
import numpy as np
import plotly.express as px

# Step 1: Create the original dataframe
df = pd.read_excel("Test data112225.xlsx")

df

,P ID,Project,Total Contract Value,Strategic Value,Customer Intimacy,Capability,Solution Complexity,Implemention Risk,Opportunity value score,Delivery Confidence Score
0,2,ProjectAA,2,5,3,5,5,3,NaN,NaN
1,3,ProjectB,1,3,5,5,3,1,NaN,NaN
2,4,ProjectAB,5,4,2,4,4,4,NaN,NaN
3,5,ProjectC,5,2,1,2,3,5,NaN,NaN
4,6,ProjectCC,2,4,4,4,3,3,NaN,NaN
5,7,Project D,2,3,4,5,2,3,NaN,NaN

In [46]:
df["PID"] = "P" + df["P ID"].astype(str)
df["Opportunity Value"] = (df["Total Contract Value "] + df["Strategic Value "] + df["Customer Intimacy"]) / 3
df["Delivery Confidence"] =(df["Capability "] + df["Solution Complexity"] + 5 - df["Implemention Risk"]) / 3
df = df.round(2)
df

,P ID,Project,Total Contract Value,Strategic Value,Customer Intimacy,Capability,Solution Complexity,Implemention Risk,Opportunity value score,Delivery Confidence Score,PID,Opportunity Value,Delivery Confidence
0,2,ProjectAA,2,5,3,5,5,3,NaN,NaN,P2,3.33,4.00
1,3,ProjectB,1,3,5,5,3,1,NaN,NaN,P3,3.00,4.00
2,4,ProjectAB,5,4,2,4,4,4,NaN,NaN,P4,3.67,3.00
3,5,ProjectC,5,2,1,2,3,5,NaN,NaN,P5,2.67,1.67
4,6,ProjectCC,2,4,4,4,3,3,NaN,NaN,P6,3.33,3.00
5,7,Project D,2,3,4,5,2,3,NaN,NaN,P7,3.00,3.00

In [47]:
# Step 2: Consolidate projects with same Metric A & Metric B
df_grouped = (
    df.groupby(["Opportunity Value", "Delivery Confidence"])["PID"]
      .apply(lambda names: "/".join(names))  # concatenate names
      .reset_index()
)

# Step 3: Create Magic Quadrant chart
fig = px.scatter(
    df_grouped,
    x="Opportunity Value",
    y="Delivery Confidence",
    text="PID",
    title="Magic Quadrant",
)

# Add quadrant lines at midpoint (3)
fig.add_shape(type="line", x0=3, y0=1, x1=3, y1=5, line=dict(color="gray", dash="dash"))
fig.add_shape(type="line", x0=1, y0=3, x1=5, y1=3, line=dict(color="gray", dash="dash"))

# Adjust text labels
fig.update_traces(textposition="top center")

# Force square aspect ratio and integer ticks
#
fig.update_layout(
    yaxis=dict(scaleanchor="x"),
    # yaxis=dict(scaleanchor="x", dtick=1),
    # xaxis=dict(dtick=1),
    width=600,
    height=600
)

fig.show()

In [49]:
df.to_excel("Output.xlsx", index=False)